import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../app/globals.css";
import { Grid } from "@mui/material";
import HeaderTabs from "@/components/work/HeaderTabs";
import Navbar from "@/components/Navbar";
import { NProgress } from "@/components/loader/Nprogress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Ahexbot",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NProgress />
                <Navbar />
                <Grid container sx={{ backgroundColor: "#ffffff", }}>
                    <Grid item xs={12} sm={9} md={9}>
                        {children}
                    </Grid>
                    <Grid item xs={12} sm={3} md={3}>
                        <HeaderTabs />
                    </Grid>
                </Grid>
            </body>
        </html>
    );
}
