import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Provider";
import { Toaster } from "react-hot-toast";
import StoreProvider from "./StoreProvider";
import { NProgress } from "@/components/loader/Nprogress";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Ahexbot",
  description: "Generated by create next app",
  icons:[]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <StoreProvider>
            <Toaster />
            <NProgress />
            {children}
          </StoreProvider>  
        </AuthProvider>
      </body>
    </html>
  );
}
